# Generated by Django 6.1 on 2026-08-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tier',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
