# Generated by Django 6.1 on 2026-08-28 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_tier_stripe_price_id_tier_stripe_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tier',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('creator', 'level'), name='unique_active_tier_level_per_creator'),
        ),
    ]
