# Generated by Django 6.1 on 2026-08-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_position_x',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_position_y',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
