# Generated by Django 6.1 on 2026-08-23 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collections/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(limit_choices_to={'is_creator': True}, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('text', 'Text')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='content/media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='content/thumbnails/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position within its Collection, if any.')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='content.collection')),
                ('creator', models.ForeignKey(limit_choices_to={'is_creator': True}, on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to=settings.AUTH_USER_MODEL)),
                ('minimum_tier', models.ForeignKey(blank=True, help_text='Leave empty for content visible to everyone, free.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_content', to='tiers.tier')),
            ],
            options={
                'ordering': ['collection', 'order', '-created_at'],
            },
        ),
    ]
