# Generated by Django 6.1 on 2026-08-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('audio', 'Audio'), ('text', 'Text')], max_length=10),
        ),
    ]
