# Generated by Django 6.1 on 2026-08-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
