# Generated by Django 6.1 on 2026-08-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_is_featured'),
        ('tiers', '0003_alter_tier_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='minimum_tier',
            field=models.ForeignKey(blank=True, help_text='Every item inside this collection inherits this tier automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_collections', to='tiers.tier'),
        ),
    ]
