# Generated by Django 6.1 on 2026-08-30 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_content_minimum_tier'),
        ('tiers', '0003_alter_tier_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='minimum_tier',
            field=models.ForeignKey(blank=True, help_text='Minimum subscription tier required to access this collection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections_with_tier', to='tiers.tier'),
        ),
        migrations.AlterField(
            model_name='content',
            name='minimum_tier',
            field=models.ForeignKey(blank=True, help_text='Minimum subscription tier required to access this content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_content', to='tiers.tier'),
        ),
    ]
