# Generated by Django 6.1 on 2026-08-25 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past due'), ('expired', 'Expired')], default='active', max_length=10)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('current_period_end', models.DateTimeField(help_text='When the currently paid period ends — drives renewal and scheduled downgrades.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(limit_choices_to={'is_creator': True}, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('pending_tier', models.ForeignKey(blank=True, help_text='Set on downgrade: takes effect at current_period_end instead of immediately.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='tiers.tier')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(help_text='The tier currently granting access.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tiers.tier')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('subscriber', 'creator'), name='unique_active_subscription_per_creator')],
            },
        ),
    ]
